services:
  - type: web
    name: intelliproc-dual-proctoring-system
    env: node
    plan: free
    buildCommand: npm install && cd frontend && npm install --legacy-peer-deps --include=dev && BUILD_PATH=dist npm run build
    startCommand: node backend/server.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
